name: CI # Workflow name
on: [push, pull_request] # list of events that triggers this workflow
jobs: # actions to execute when triggered
  build: # build action
    runs-on: ubuntu-22.04 # run on Ubuntu 22.04

    steps: # commands to execute
      - uses: actions/checkout@v3 # ?
      - name: Set up JDK 17 # Installs JDK 17
        uses: actions/setup-java@v3
        with: # provides input parameters to the setup action
          java-version: 17
          distribution: 'temurin'
      - name: Build using Gradle # Builds project
        run: ./gradlew build